{% set name = "mapgenerator" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mapgenerator-{{ version }}.tar.gz
  sha256: 882162b50c1b999b569f322f05d3e07b8c2b3a7c4e88c3805304612a46b05c14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cartopy
    - chart-studio
    - config
    - configargparse
    - lxml
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - plotly
    - python >=3.6

test:
  requires:
    - pip
    - pytest
  imports:
    - mapgenerator
    - mapgenerator.plotting.timeseries
  commands:
    - pip check

about:
  home: https://pypi.org/project/MapGenerator
  summary: Map Generator is a tool that provides easy to use 2D plotting functions for Earth sciences datasets.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zklaus
